const Constants = {
    SET_SEARCH_QUERY:'SET_SEARCH_QUERY',
    SET_SELECTED:'SET_SELECTED',
    SORT_LIST:'SORT_LIST',
    SET_FILTERED_BUDDIES:'SET_FILTERED_BUDDIES',
    ADD_BUDDY:'ADD_BUDDY',
    REMOVE_BUDDY:'REMOVE_BUDDY',
    CANCEL_DELETE:'CANCEL_DELETE',
    SHOW_ALERT:'SHOW_ALERT',
    CONFIRM_DELETE:'CONFIRM_DELETE',
    SET_VIEW:'SET_VIEW',
    ALERT_CONFIRM:'ALERT_CONFIRM',
    ALERT_ERROR:'ALERT_ERROR'
};

export default Constants;